### ISSUE TITLE
K8s inventory plugin documentation has wrong connection parameter name in the example.

### ISSUE THREAD

**Issue by sharafcmr** [ansible-collections/community.kubernetes#101]
##### SUMMARY
The actual key/parameter name for adding kubernetes api token to the k8s inventory plugin under the connection properties of "k8s" plugin is "[api_token](https://github.com/ansible-collections/community.kubernetes/blob/9ccec43c6e8120a721d4c6b623075a94f8ed2f3f/plugins/inventory/k8s.py#L48)".
```
             api_key:
              description:
              - Token used to authenticate with the API. Can also be specified via K8S_AUTH_API_KEY environment variable.
```

 However the [example mentioned in the k8s plugin ](https://github.com/ansible-collections/community.kubernetes/blob/9ccec43c6e8120a721d4c6b623075a94f8ed2f3f/plugins/inventory/k8s.py#L96-L100)has a wrong parameter  name, "token" for holding the same api token. 
EXAMPLES = 
```
# File must be named k8s.yaml or k8s.yml
# Authenticate with token, and return all pods and services for all namespaces
plugin: k8s
connections:
  - host: https://192.168.64.4:8443
    token: xxxxxxxxxxxxxxxx
    validate_certs: false
# Use default config (~/.kube/config) file and active context, and return objects for a specific namespace
plugin: k8s
connections:
  - namespaces:
    - testing
# Use a custom config file, and a specific context.
plugin: k8s
connections:
  - kubeconfig: /path/to/config
    context: 'awx/192-168-64-4:8443/developer'
```

Since the same wrong documentation is being displayed in [official ansible documentation](https://docs.ansible.com/ansible/latest/plugins/inventory/k8s.html#k8s-kubernetes-k8s-inventory-source)  it is misleading the user to a wrong k8s.yml file resulting an error while running the inventory.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes inventory plugin source

##### ANSIBLE VERSION

```
ansible 2.9.9

```

##### CONFIGURATION

Wrong documentation
```
plugin: k8s
connections:
  - host: https://192.168.64.4:8443
    token: xxxxxxxxxxxxxxxx
    validate_certs: false
```
The example should be corrected as below:
```
plugin: k8s
connections:
  - host: https://192.168.64.4:8443
    api_key: xxxxxxxxxxxxxxxx
    validate_certs: false
```
Correction should be done in the example section of [k8s inventory plugin](https://github.com/ansible-collections/community.kubernetes/blob/9ccec43c6e8120a721d4c6b623075a94f8ed2f3f/plugins/inventory/k8s.py#L96-L100)
```
##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->


##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml

```

##### EXPECTED RESULTS
[The above mentioned example ](https://github.com/ansible-collections/community.kubernetes/blob/9ccec43c6e8120a721d4c6b623075a94f8ed2f3f/plugins/inventory/k8s.py#L96-L100)section has been corrected as below 
```
plugin: k8s
connections:
  - host: https://192.168.64.4:8443
    api_key: xxxxxxxxxxxxxxxx
    validate_certs: false
```
##### ACTUAL RESULTS

```paste below

```
