### ISSUE TITLE
Implement helm install --replace

### ISSUE THREAD

**Issue by T1loc** [ansible-collections/community.kubernetes#106]
##### SUMMARY

Implement helm install --replace

#### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

helm

##### ADDITIONAL INFORMATION

When a release is uninstalled with `helm uninstall --keep-history`, we are not able to perform a `helm upgrade -i`

```yaml
helm list --all -o yaml                                                                                                                                                                                           
- app_version: ""
  chart: xxx-xxx
  name: test
  namespace: florian
  revision: "1"
  status: uninstalled
  updated: 2020-05-27 20:07:15.487307 +0200 CEST
```

To install by reusing the release name and then keep the history
```yaml
helm install --replace --namespace=florian test test 
```

Open Questions : 
- Should we add a replace option (True/False) only available when the release status is uninstalled ?
- Any other way to answer the problem ?
