### ISSUE TITLE
Add Helm --create-namespace flag support

### ISSUE THREAD

**Issue by igrybkov** [ansible-collections/community.kubernetes#108]
##### SUMMARY

New Helm integration [suggests](https://github.com/ansible-collections/community.kubernetes/blob/0.11.0/plugins/modules/helm.py#L125) creating namespace manually because Helm 3 does not support creating a namespace for you which is not exactly true. [It has a flag](https://helm.sh/docs/faq/#automatically-creating-namespaces) `--create-namespace` that must be explicitly specified in order to make Helm create a namespace. I'm suggesting to add this flag support into Helm module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

helm

##### ADDITIONAL INFORMATION

```yaml
- name: Deploy latest version of Grafana chart inside monitoring namespace with values
  helm:
    name: test
    chart_ref: stable/grafana
    release_namespace: monitoring
    create_namespace: true
    values:
      replicas: 2
```
