### ISSUE TITLE
include an optional --atomic flag with helm install and upgrade

### ISSUE THREAD

**Issue by abhiTamrakar** [ansible-collections/community.kubernetes#109]
##### SUMMARY

Helm installation includes ensuring the release is deployed successfully and in most cases can be rolled back automatically without ending up in FAILED state.
helm provides --atomic flag for that purpose and it include --wait as well.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

https://github.com/ansible-collections/community.kubernetes/blob/master/plugins/modules/helm.py

##### ADDITIONAL INFORMATION

```yaml
- name: install a stable chart for grafana using --atomic
   helm:
      name: test
      chart_ref: stable/grafana
      release_namespace: monitoring
      atomic: true
      values:
        replicas: 2
```
