### ISSUE TITLE
Helm plugin module

### ISSUE THREAD

**Issue by stanislaw55** [ansible-collections/community.kubernetes#134]
##### SUMMARY
Helm tool provides rich set of plugins that can be used with it. There could be new Ansible module which would allow installing, updating and removing them.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community.kubernetes.helm_plugin` - that could be the name for new module

##### ADDITIONAL INFORMATION

```yaml
- name: Install Helm diff plugin
  helm_plugin:
    source: https://github.com/databus23/helm-diff
    version: master
    state: present
```
