### ISSUE TITLE
k8s support Deployment(Config) rollouts and rollbacks

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.kubernetes#138]
_From @djzager on Feb 11, 2019 20:58_

##### SUMMARY

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

In the same way that the [`k8s_scale` module](https://docs.ansible.com/ansible/latest/modules/k8s_scale_module.html#k8s-scale-module) allows you to scale up|down Kubernetes objects that support the scale subresource, it would be great to have a supported method for rolling out and rolling back Deployments (and DeploymentConfigs).

A specific use case that I have in mind would be to tie the configuration of the application (stored in a ConfigMap) with the version of the Deployment such that when the ConfigMap is updated (instead of deleting all of the active pods) we roll out a new version of the application.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Maybe one for `k8s_rollout` and another for `k8s_rollback`?

##### ADDITIONAL INFORMATION

```yaml
handlers:
  - name: upgrade myapp
    k8s_rollout:
      api_version: v1
      kind: Deployment
      name: myapp
      namespace: myapp-namespace

tasks:
  # Set the configmap, upgrade when changed
  - name: set configmap
    k8s:
      state: present
      definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: myapp-config
          namespace: myapp-namespace
        data:
          foo: bar
    notify: upgrade myapp
```

_Copied from original issue: ansible/ansible#52046_
