### ISSUE TITLE
Helm module should use K8S_AUTH_KUBECONFIG when kubeconfig_path isn't specified

### ISSUE THREAD

**Issue by joao-fidalgo** [ansible-collections/community.kubernetes#140]
##### SUMMARY
Helm module should use K8S_AUTH_KUBECONFIG when kubeconfig_path isn't specified

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
helm

##### ADDITIONAL INFORMATION
This change would normalize behaviour between modules.

```yaml
- hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - community.kubernetes

  environment:
    K8S_AUTH_KUBECONFIG: "/tmp/kubeconfig.yml"

  tasks:
    - name: install rancher using helm
       helm:
        chart_ref: rancher-stable/rancher
        name: rancher
        namespace: cattle-system
```
