### ISSUE TITLE
k8s_log istio support

### ISSUE THREAD

**Issue by ElioLopez-md** [ansible-collections/community.kubernetes#142]
##### SUMMARY
Hello,
Seems like currently the k8s_logs module is not supporting Istio enabled clusters.

When using Istio and you create a pod, a sidecar pod is automatically created.
For example, this won't work:
```yaml
elopez@MacBook-Pro K8s_Ansible_test % kubectl get pods --namespace=developer-portal                                         
NAME                                            READY   STATUS    RESTARTS   AGE
developer-portal-backend-v1-5b7cdb9885-6v4v8    2/2     Running   0          8d

elopez@MacBook-Pro K8s_Ansible_test % kubectl logs developer-portal-backend-v1-5b7cdb9885-6v4v8 --namespace=developer-portal 
error: a container name must be specified for pod developer-portal-backend-v1-5b7cdb9885-6v4v8, choose one of: [developer-portal-backend istio-proxy] or one of the init containers: [istio-init]
```
instead of that, you should specify the container:

```yaml
elopez@MacBook-Pro K8s_Ansible_test % kubectl logs developer-portal-backend-v1-5b7cdb9885-6v4v8 developer-portal-backend --namespace=developer-portal 
[Nest] 1   - 06/17/2020, 12:58:49 PM   [NestFactory] Starting Nest application...
[Nest] 1   - 06/17/2020, 12:58:49 PM   [InstanceLoader] FeatureModule dependencies initialized +124ms
[Nest] 1   - 06/17/2020, 12:58:49 PM   [InstanceLoader] CustomizationModule dependencies initialized +1ms
```
and this is somehow the error we are getting when using the module:

```yaml
openshift.dynamic.exceptions.BadRequestError: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 25 Jun 2020 12:09:50 GMT', 'Content-Length': '303', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod developer-portal-frontend-v1-57698ccbfd-pjm87, choose one of: [developer-portal-frontend istio-proxy] or one of the init containers: [istio-init]","reason":"BadRequest","code":400}
```

##### ISSUE TYPE
- k8s_log Istio mode enabled not supported

##### COMPONENT NAME
k8s_log module

##### ADDITIONAL INFORMATION
This will be great to use it when having an Istio enabled cluster
