### ISSUE TITLE
Helm: Integer values should not be casted as string

### ISSUE THREAD

**Issue by jatinderjawanda** [ansible-collections/community.kubernetes#143]
##### SUMMARY
While deploying `https://hub.helm.sh/charts/elastic/elasticsearch`, encountered a issue. Helm module cast integer values to string in temporary generated values.yml file under /tmp/ directory.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
HELM

##### ANSIBLE VERSION

```
ansible 2.9.9
python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### STEPS TO REPRODUCE

Its happening when actual variable is under indentation.
for eg:
```
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000
```
however, if u have the variable at parent level then behavior is as expected:
for eg:

```
    runAsUser: 1000
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
```
commands
```
shell> kubectl create ns elastic
shell> helm repo add elastic https://helm.elastic.co
```
Inventory file
```
vi test
[k8s]
master1
```
playbook
```
vi elastic.yml
---

- name: Gather Facts for all hosts
  hosts: all
  gather_facts: true

- name: Install | elasticsearch
  vars:
    httpPort: 9200
    transportPort: 9300
    maxUnavailable:
    minimumMasterNodes:
    replicas:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000
  hosts: k8s
  gather_facts: true
  any_errors_fatal: true
  become: true
  run_once: true
  tasks:
    - name: Install | elasticsearch cluster
      community.kubernetes.helm:
        name: "elastic"
        chart_ref: "elastic/elasticsearch"
        chart_version: "7.8.0"
        release_namespace: "elastic"
        state: present
        release_values:
          httpPort: "{{ httpPort }}"
          transportPort: "{{ transportPort }}"
          maxUnavailable: "{{ maxUnavailable }}"
          minimumMasterNodes: "{{ minimumMasterNodes }}"
          replicas: "{{ replicas }}"
          podSecurityContext:
            fsGroup: "{{ podSecurityContext.fsGroup }}"
            runAsUser: "{{ podSecurityContext.runAsUser }}"
          securityContext:
            capabilities:
              drop: "{{ securityContext.capabilities.drop }}"
            runAsNonRoot: "{{ securityContext.runAsNonRoot }}"
            runAsUser: "{{ securityContext.runAsUser }}"

shell> ansible-playbook -i test playbooks/elastic.yml -k
```

##### ACTUAL RESULTS

```
fatal: [master1]: FAILED! => {
    "changed": false,
    "command": "/bin/helm --namespace=elastic --version=7.8.0 upgrade -i --reset-values -f=/tmp/tmpopL2l6.yml elastic elastic/elasticsearch"
}

MSG:

Failure when executing Helm command. Exited 1.
stdout: Release "elastic" does not exist. Installing it now.

stderr: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext.runAsUser): invalid type for io.k8s.api.core.v1.SecurityContext.runAsUser: got "string", expected "integer", ValidationError(StatefulSet.spec.template.spec.securityContext.fsGroup): invalid type for io.k8s.api.core.v1.PodSecurityContext.fsGroup: got "string", expected "integer", ValidationError(StatefulSet.spec.template.spec.securityContext.runAsUser): invalid type for io.k8s.api.core.v1.PodSecurityContext.runAsUser: got "string", expected "integer"]

cat /tmp/tmpopL2l6.yml
httpPort: 9200
maxUnavailable: null
minimumMasterNodes: null
podSecurityContext:
  fsGroup: '1000'
  runAsUser: '1000'
replicas: null
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: '1000'
transportPort: 9300
```

**Comment by geerlingguy** [comment]
If you replace `runAsUser: "{{ securityContext.runAsUser }}"` with `runAsUser: 1000` does it work? It could be a problem where when you use a jinja var, you have to cast it to an int explicitly, e.g.:

```yaml
            runAsUser: "{{ securityContext.runAsUser | int }}"
```

**Comment by jatinderjawanda** [comment]
> If you replace `runAsUser: "{{ securityContext.runAsUser }}"` with `runAsUser: 1000` does it work? It could be a problem where when you use a jinja var, you have to cast it to an int explicitly, e.g.:
> 
> ```yaml
>             runAsUser: "{{ securityContext.runAsUser | int }}"
> ```

Yes, I tried this too but no luck here. if you see there are other integer values like 9200 and 9300 in generated file  and they are coming as integer. So I try defining values directly without indentation and then the generated file has the right values of integer type.

**Comment by jatinderjawanda** [comment]
To move ahead, I removed the indentation for those variables. So, here is my current vars section.
```
- name: Install | elasticsearch
  vars:
    httpPort: 9200
    transportPort: 9300
    securityContext_runAsUser: 1000
    maxUnavailable: 1
    minimumMasterNodes: 2
    replicas: 3
    podSecurityContext_fsGroup: 1000
    podSecurityContext_runAsUser: 1000
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
```

**Comment by Akasurde** [comment]
@jatinderjawanda This is due to how Ansible parses variables. I am quoting @sivel's comment 

```
Unfortunately due to how jinja2 works, it technically only has the ability to return strings. Any time you use jinja2 templating, the result comes out as a string. So while |int is internally converting the value to an int, the final result from jinja2 is a string.
```

But you can use Jinja Native datatype to solve this problem - 

So, Add this value in `defaults` section of ansible.cfg

```ini
[defaults]
jinja2_native = True
```

And in playbook -

```yaml
...
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: !!int 1000
...
```

So this will get as `release_values` in yml file as 

```
...
runAsNonRoot: 1000
...
```

Please try this and let me know. Thanks.
