### ISSUE TITLE
I want to use the value of with_items in a jinja2 template via the k8s module

### ISSUE THREAD

**Issue by ponkio-o** [ansible-collections/community.kubernetes#147]
I am trying to define a resource on Kubernetes using the [k8s](https://docs.ansible.com/ansible/latest/modules/k8s_module.html) module.

##### SUMMARY

Use a file similar to the one below to match the username listed in with_items We're going to define Deployment, Service, and Ingress as
Service and Deployment can be created successfully, but not for Ingress.
(`mission_type` and `services` is used in a separate process.)

`/root/workdir/hosts`
```
host01 ansible_ssh_user=root ansible_connection=local
```

`/root/workdir/playbook.yml`
```yaml
- hosts: localhost
  tasks:
    - include_tasks: create_environment.yml
      with_items:
        - name: user1
          mission_type: sre
          services:
            - web
          state: present
        - name: user2
          mission_type: web
          services:
            - web
          state: present
      loop_control:
        loop_var: user
```

`create_environment.yml`
```yaml
- name: Create Pod
  when: "web' in user.services"
  k8s:
    namespace: default
    state: "{{ user.state }}"
    definition: "{{ lookup('template', '/root/workdir/manifest/deployment.yml.j2') }}"

- name: Create Service
  when: "'web' in user.services"
  k8s:
    namespace: default
    state: "{{ user.state }}"
    definition: "{{ lookup('template', '/root/workdir/manifest/service.yml.j2') }}"

- name: Create Ingress
  when: "'web' in user.services"
  k8s:
    namespace: default
    state: "{{ user.state }}"
    definition: "{{ lookup('template', '/root/workdir/manifest/ingress.yml.j2') }}"
```

`/root/workdir/manifest/deployment.yml.j2`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dev-{{ user.name }}"
  labels:
    run: "dev-{{ user.name }}"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "dev-{{ user.name }}"
  template:
    metadata:
      labels:
        run: "dev-{{ user.name }}"
    spec:
      containers:
      - name: "dev-{{ user.name }}"
        image: <image>
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "500Mi"
        ports:
        - containerPort: 80
```

`/root/workdir/manifest/service.yml.j2`
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    run: "dev-{{ user.name }}"
  name: "dev-{{ user.name }}"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: "dev-{{ user.name }}"
```

`/root/workdir/manifest/ingress.yml.j2`
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
{% for item in user %}
    - host: "d-{{ item.name }}.example.com"
      http:
        paths:
          - backend:
              serviceName: "dev-{{ item.name }}"
              servicePort: 80
{% endfor %}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

[k8s_module](https://docs.ansible.com/ansible/latest/modules/k8s_module.html)

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
Empty
```

##### OS / ENVIRONMENT

Dockerfile
```
FROM centos:7

RUN yum install epel-release -y && \
    yum -y update && \
    yum --enablerepo=epel install python2-pip.noarch -y && \
    yum install openssh-server -y && \
    yum install openssh-clients -y && \
    yum reinstall glibc-common -y && \
    yum install sshpass -y && \
    yum remove python27-chardet.noarch -y && \
    pip install --upgrade pip && \
    pip install ansible && \
    pip install pywinrm && \
    yum clean all

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN yum -y install unzip
RUN unzip awscliv2.zip
RUN ./aws/install
RUN mkdir ~/.aws

RUN pip install jinja2==2.11.1 && \
    pip install netaddr==0.7.19 && \
    pip install pbr==5.4.4 && \
    pip install hvac==0.10.0 && \
    pip install jmespath==0.9.5 && \
    pip install ruamel.yaml==0.16.10

RUN pip install --upgrade pip setuptools
RUN pip install openshift==0.11.0 --ignore-installed

RUN mkdir /root/workdir
RUN mkdir ~/.kube

ENV LANG ja_JP.UTF-8

WORKDIR /root/workdir

CMD ["/bin/bash"]
```

##### STEPS TO REPRODUCE

Since we are using EKS, we need to add aws credentials and .kube/config to Execute the following command on the mounted container.

```
$ ansible-playbook -i hosts playbook.yml
```

```yaml
- hosts: localhost
  tasks:
    - include_tasks: create_environment.yml
      with_items:
        - name: user1
          mission_type: sre
          services:
            - web
          state: present
        - name: user2
          mission_type: web
          services:
            - web
          state: present
      loop_control:
        loop_var: user
```

##### EXPECTED RESULTS

I was expect to create an Ingress resource in the following format.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: "d-user1.example.com"
      http:
        paths:
          - backend:
              serviceName: "dev-user1"
              servicePort: 80
    - host: "d-user2.example.com"
      http:
        paths:
          - backend:
              serviceName: "dev-user2"
              servicePort: 80
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i hosts playbook.yml -vvvv
~~~~
TASK [Create Ingress] *************************************************************************************
task path: /root/workdir/create_environment.yml:15
File lookup using /root/workdir/manifest/ingress.yml.j2 as file
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'\n\nThe error appears to be in '/root/workdir/create_environment.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Ingress\n  ^ here\n"
}
```
