### ISSUE TITLE
Creating new ingress resources

### ISSUE THREAD

**Issue by Mierpo** [ansible-collections/community.kubernetes#162]
##### SUMMARY
Allow users to create new Ingress resources in Kubernetes

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
kind: Ingress

##### ADDITIONAL INFORMATION
This feature would add the ability to create new Ingress resources to Kubernetes clusters.

I couldn't find information on how to achieve this using Ansible modules, besides calling the k8s API directly with a "shell" module. Setting up Ingress is quite an important part of the k8s cluster. I believe having this feature would increase the usability and value of this collection.

Example yaml definition that people might want to use when using the kubernetes.community ansible package:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: barbar
  namespace: foobar
spec:
  rules:
  - host: service.url.here
    http:
      paths:
      - backend:
          serviceName: barbarS
          servicePort: 80
        path: /(.*)
```

**Comment by Mierpo** [comment]
This can actually be done with this:

```yaml
- name: Add influxdb service ingress
  k8s:
    definition:
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        annotations:
          kubernetes.io/ingress.class: nginx
        name: barbar
        namespace: foobar
      spec:
        rules:
        - host: service.url.here
          http:
            paths:
            - backend:
                serviceName: barbarS
                servicePort: 80
              path: /(.*)
```
