### ISSUE TITLE
Support for kustomize in the k8s module.

### ISSUE THREAD

**Issue by christianh814** [ansible-collections/community.kubernetes#163]
##### SUMMARY

I would like to use kustomize with the `k8s` module. This will allow someone to be able to supply a directory or URI with a `kustomize.yaml` file in it.

This should emulate what `kubectl -k /path/to/dir` does (as close as possible).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Ideally, I would like to have this as part of the `k8s` module. But wouldn't mind having a separate `kustomize` module (maybe `k8s_kustomize`?)

##### ADDITIONAL INFORMATION

I assume the k8s api is being hit, so comparing it to the functionality that the `kubectl` has isn't apples to apples. But, it would be great to "expand" the `src` option to something like this..

Equivalent to: `kubectl create -k /path/to/some/kustomizedir`

```yaml
- name: Create objects from a local directory that has a kustomize.yaml file
  k8s:
    state: present
    src: /path/to/some/kustomizedir
    kustomize: true
```

Equivalent to: `kubectl create -k https://github.com/username/some/kustomizedir`

```yaml
- name: Create objects from a remote dir that has a kustomize.yaml file
  k8s:
    state: present
    src: https://github.com/username/some/kustomizedir
    kustomize: true
```

**Comment by christianh814** [comment]
Or maybe just add `kustomize` as an option?

Something like...

```yaml
- name: Create objects from a local directory that has a kustomize.yaml file
  k8s:
    state: present
    kustomize: /path/to/some/kustomizedir
```

and...

```yaml
- name: Create objects from a remote dir that has a kustomize.yaml file
  k8s:
    state: present
    kustomize: https://github.com/username/some/kustomizedir
```

I'll let others chime in.

**Comment by geerlingguy** [comment]
cc @fabianvf — I believe you were actually exploring a `kustomize` module as part of your work with the Operator Framework. It would be interesting to see what kind of ideas you have for it too.

**Comment by tylerauerbeck** [comment]
@christianh814 The question I have here is what version of `kustomize` would you support here? Do you stick with 2.X to keep in line with what is bundled with `kubectl`, a more recent release? Or do you allow this to be configurable (which seems like it could get fairly complex)

**Comment by christianh814** [comment]
@tylerauerbeck 

I think that it should be consistent with what's packaged with `kubectl`. Since my idea here is to emulate `kubectl`

**Comment by fabianvf** [comment]
For our molecule testing in operator-sdk we were hitting some annoying issues where our testing overlays had to be pretty huge and modified on disk during tests (with changes we definitely had no intention of keeping). Because of that, I was playing with the idea of a `kustomize` module that would allow you to inline `kustomization` that Ansible would lay down as an overlay. It would return the result of `kustomize build` and then you could loop over the resources and create them as normal with the `k8s` module. This would provide value beyond just wrapping the CLI tool, and at least for us would simplify some of our testing scenarios considerably. Adding it as an argument to the `k8s` module does make sense to me, though the module is already pretty large and I feel like the concerns are separate enough that it could make sense to split it out regardless.

**Comment by tima** [comment]
@fabianvf what you describe sounds good though I think a `kustomize` lookup function similar to the template or file lookups would be more appropriate. Something like...

```
- name: apply resources
  k8s:
    definition: "{{ lookup('kustomize', item) }}"
  with_items:
    - foo.yml
    - bar.yml
```

Doing so would be consistent to how a user reads and template-ize external definition files now.

```
- name: create foo configmap
  k8s:
    definition: "{{ lookup('template', '/foo.yml') | from_yaml }}"
``` 

I would be opposed to building kustomize template processing functionality directly into the `k8s` module. Jinja2 is Ansible's standard built-in template engine across all use cases. It will get really messy in the code and for users if we start building in each and every template language and engine across all of the various domains Ansible spans.
