### ISSUE TITLE
Support for helm secrets?

### ISSUE THREAD

**Issue by alexgeek** [ansible-collections/community.kubernetes#164]
Sorry for not using the templates provided but nothing seemed relevant. 
I was just wondering if helm secrets is supported?

**Comment by Akasurde** [comment]
@alexgeek Are you referring this helm plugin [secrets](https://github.com/zendesk/helm-secrets)?

**Comment by alexgeek** [comment]
Yes indeed.

**Comment by mes5k** [comment]
I was able to get rid of `helm secrets` from my chart by using `ansible-vault` to store hard-coded secrets.  My task looks something like this:
```
---
- include_vars: vault.yml

- name: Install Helm chart
  community.kubernetes.helm:
    release_name: "{{ helm_release }}"
    release_namespace: "{{ helm_namespace }}"
    release_values: "{{ lookup('template', '../files/secrets.yaml.j2') | from_yaml  }}"
    chart_ref: "{{ chart_ref }}"
    chart_version: "{{ chart_version }}"
```
All encrypted secrets are stored in `vault.yml`. Those variables get substituted into the `../files/secrets.yaml.j2` template that gets passed in as my release values to helm.  I also use the [password lookup plugin](https://docs.ansible.com/ansible/latest/plugins/lookup/password.html) to generate random passwords.
