### ISSUE TITLE
Missing modules/plugins

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.kubernetes#165]
##### SUMMARY
Ansible-base is redirecting several 2.9 modules and lookup plugins to this collection, which do not exist here:

* ansible-base modules k8s_facts redirects to community.kubernetes.k8s_facts (to be removed in Ansible 2.13, alias of k8s_info)
* ansible-base modules k8s_raw redirects to community.kubernetes.k8s_raw (was deprecated, but had no explicit removal version)
* ansible-base modules openshift_raw redirects to community.kubernetes.openshift_raw (was deprecated, but had no explicit removal version)
* ansible-base modules openshift_scale redirects to community.kubernetes.openshift_scale (was deprecated, but had no explicit removal version)
* ansible-base lookup openshift redirects to community.kubernetes.openshift (was deprecated, but had no explicit removal version)

For k8s_facts, I would add the following to `meta/runtime.yml`:
```.yaml
plugin_routing:
  modules:
    k8s_facts:
      redirect: community.kubernetes.k8s_info
      deprecation:
        removal_version: 2.0.0
        warning_text: Use community.kubernetes.k8s_info instead.
```
The others should be tombstoned, if they are to be removed for Ansible 2.10:
```
plugin_routing:
  modules:
    k8s_raw:
      tombstone:
        removal_version: 0.1.0  # probably put the first version here, since it never was in the collection?
        warning_text: The k8s_raw module was deprecated for some time and has been removed.
    ...
  lookup:
    openshift:
      tombstone:
        removal_version: 0.1.0  # probably put the first version here, since it never was in the collection?
        warning_text: The openshift lookup plugin was deprecated for some time and has been removed.
```
Please adjust the texts, I don't know the background of the deprecations/removals :)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
collection
