### ISSUE TITLE
k8s lookup plugin fails to decode ConfigMap using label_select

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.kubernetes#178]
_From @jmazzitelli on Apr 05, 2019 06:12_

##### SUMMARY

Have a ConfigMap in Kubernetes, try to look it up using label_select:

```
lookup('k8s', label_select='app=kiali', namespace='default', api_version='v1', kind='ConfigMap')
```

See it fail:

```
"An unhandled exception occurred while running the lookup plugin 'k8s'. Error was a <type 'exceptions.UnicodeDecodeError'>, original message: 'ascii' codec can't decode byte 0xf0 in position 255532: ordinal not in range(128)"
```

Now look it up using resource_name (not label_select) and see it succeed:

```
lookup('k8s', resource_name='kiali', namespace='default', api_version='v1', kind='ConfigMap')
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s lookup plugin

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/jmazzite/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jmazzite/source/ansible/lib/ansible
  executable location = /home/jmazzite/source/ansible/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
(empty results)
```

##### OS / ENVIRONMENT
OpenShift 3.11

##### STEPS TO REPRODUCE

Create a simple ConfigMap in your cluster:

```
$ cat << EOM | kubectl create -n default -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
data:
  config.yaml: |
    foo: bar
EOM
```

Confirm you have your config map:

```
$ kubectl get configmap -n default kiali
NAME      DATA      AGE
kiali     1         11s
```

This does not work:

```yaml
- debug:
    msg: "{{ k8s_item }}"
  with_items:
  - "{{ lookup('k8s', label_select='app=kiali', namespace='default', api_version='v1', kind='ConfigMap') }}"
  loop_control:
    loop_var: k8s_item
```

This works:

```yaml
- debug:
    msg: "{{ k8s_item }}"
  with_items:
  - "{{ lookup('k8s', resource_name='kiali', namespace='default', api_version='v1', kind='ConfigMap') }}"
  loop_control:
    loop_var: k8s_item
```

##### EXPECTED RESULTS

Querying with label_select should return the same ConfigMap that returns when querying by name.

##### ACTUAL RESULTS

Querying with label_select fails (but querying by name works). The error when using label_select is:

```paste below
"An unhandled exception occurred while running the lookup plugin 'k8s'. Error was a <type 'exceptions.UnicodeDecodeError'>, original message: 'ascii' codec can't decode byte 0xf0 in position 255532: ordinal not in range(128)"
```

_Copied from original issue: ansible/ansible#54889_

**Comment by Akasurde** [comment]
_From @fabianvf on Oct 25, 2019 17:02_

@jmazzitelli I think the proper argument to the lookup plugin is `label_selector`, not `label_select`, I'm not sure if that would cause this issue or not. Generally I recommend using the `k8s_facts` (called `k8s_info` in 2.9+) instead of the lookup plugin, as it will behave more similarly to the `k8s` module in terms of how it connects to the cluster.

**Comment by jmazzitelli** [comment]
> Generally I recommend using the `k8s_facts` (called `k8s_info` in 2.9+) instead of the lookup plugin

In this case, lookup is being used specifically to build up items in a loop, so using k8s_info is not available for me here. For example, what if I needed to do something like this:

```
- name: Delete a bunch of resources
  k8s:
    state: absent
    api_version: "{{ k8s_item.apiVersion }}"
    kind: "{{ k8s_item.kind }}"
    namespace: foo
    name: "{{ k8s_item.metadata.name }}"
  register: delete_result
  until: delete_result.result == {} or (delete_result.result.status is defined and delete_result.result.status == "Success")
  retries: 6
  delay: 10
  when:
  - k8s_item is defined
  - k8s_item.apiVersion is defined
  - k8s_item.kind is defined
  - k8s_item.metadata is defined
  - k8s_item.metadata.name is defined
  with_items:
  - "{{ query('k8s', namespace=foo, kind='Ingress', resource_name='myingress', api_version='extensions/v1beta1') }}"
  - "{{ query('k8s', namespace=foo, kind='Deployment', resource_name='mydeployment', api_version='apps/v1') }}"
  - "{{ query('k8s', namespace=foo, kind='Pod', resource_name='mypod', api_version='v1') }}"
  - "{{ query('k8s', namespace=foo, kind='Service', resource_name='kiali', api_version='v1') }}"
  ...and more...
  loop_control:
    loop_var: k8s_item
```

In the example above, you can see I'm using `query` not lookup (it's been a while since I had to work around this issue - I think that was my solution - use query instead), but the idea is the same - what if I used `lookup` in `with_items`? Can't use k8s_info here.
