### ISSUE TITLE
support generateName or utils like that

### ISSUE THREAD

**Issue by alaypatel07** [ansible-collections/community.kubernetes#186]
##### SUMMARY

In order to make sure that resources created by k8s module has unique
name, there is some work involded to be done in ansible. kubernetes
api-server has a `metadata.generateName` field which can be used
to create a name that is within the limits of max chars allowed for the 
resource. It would be great if the k8s module allows creation of 
resources with generateName so the user does not have to take
care of limits of `metadata.Name`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s

##### ADDITIONAL INFORMATION

```yaml
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  generateName: utilitypod-
  namespace: blah-dev
  labels:
    purpose: utility-pod
spec:
  containers:
    - name: utilitypod
      image: blahblah/utilitypod:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 28800; done;" ]
      env:
        - name: KUBERNETES_SERVICE_HOST
          value: "api.dev.blah.internal"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
EOF

```

Taken from this stackoverflow thread https://stackoverflow.com/questions/48023475/add-random-string-on-kubernetes-pod-deployment-name

**Comment by Akasurde** [comment]
@alaypatel07 I would use the following task - 

```yaml
    - name: Create a pod object from an inline definition
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "utilitypod-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
            namespace: default
            labels:
              app: galaxy
              service: web
          spec:
            containers:
              - name: utilitypod
                image: busybox
```

or 

```yaml
    - set_fact:
        random_pod_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - name: create the pod with random name
      k8s:
        state: present
        definition: "{{ lookup('template', './generateName.yml') | from_yaml }}"
```

cat generateName.yml
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: utilitypod-{{ random_pod_name }}
  namespace: default
  labels: 
     app: galaxy
     service: web
spec:
  containers:
  - name: utilitypod
    image: busybox
```


Since `generateName` is only applicable for `create` whereas `k8s` module uses `apply`.

@fabianvf @tima @willthames @geerlingguy Correct me if I am wrong here.
