### ISSUE TITLE
Fix validate_certs test in molecule integration test 'full.yml'

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#24]
##### SUMMARY

As part of fixing https://github.com/ansible/ansible/pull/57418 (ansible/ansible PR https://github.com/ansible/ansible/issues/56640), a task was added to the `full.yml` test playbook which is run in molecule's `default` scenario:

```yaml
    - name: Setting validate_certs to true causes a failure
      k8s:
        name: testing
        kind: Namespace
        validate_certs: yes
      ignore_errors: yes
      register: output
    
    - name: assert that validate_certs caused a failure (and therefore was correctly translated to verify_ssl)
      assert:
        that:
          - output is failed
```

This fails now that we have molecule running tests on a full cluster (see #22) with the following message:

```
    TASK [assert that validate_certs caused a failure (and therefore was correctly translated to verify_ssl)] ***
    fatal: [localhost]: FAILED! => {
        "assertion": "output is failed",
        "changed": false,
        "evaluated_to": false,
        "msg": "Assertion failed"
    }
```

We should make it so that test is correct and passes, and/or fix the underlying bug if it's showing that it actually _doesn't_ work like it should.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

CI

##### ANSIBLE VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

  1. Uncomment the commented tasks in `molecule/default/tasks/full.yml`
  2. Run `molecule test`

##### EXPECTED RESULTS

Tests should pass.

##### ACTUAL RESULTS

Tests fail on:

```
    TASK [assert that validate_certs caused a failure (and therefore was correctly translated to verify_ssl)] ***
    fatal: [localhost]: FAILED! => {
        "assertion": "output is failed",
        "changed": false,
        "evaluated_to": false,
        "msg": "Assertion failed"
    }
```
