### ISSUE TITLE
k8s_event_info

### ISSUE THREAD

**Issue by stiller-leser** [ansible-collections/community.kubernetes#249]
##### SUMMARY

Create a new module `community.kubernetes.k8s_event_info` to be able to react to events.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`community.kubernetes`

specifically create a new module `community.kubernetes.k8s_event_info`

##### ADDITIONAL INFORMATION

`community.kubernetes.k8s_event_info` would be used to mimick the workings of `kubectl describe` or in API terms the request
```
api/v1/namespaces/operator/events?fieldSelector=involvedObject.name%3Dmy-test-service%2CinvolvedObject.namespace%3Doperator%2CinvolvedObject.kind%3DService%2CinvolvedObject.uid%3DAnUID
```

This would allow to react to events like 
```
Warning  SyncLoadBalancerFailed  8m45s (x19 over 74m)  service-controller  Error syncing load balancer: failed to ensure load balancer: failed to create listener for loadbalancer UID: Expected HTTP response code [] when accessing [POST https://network-3.openstack.com/v2.0/lbaas/listeners], but got 409 instead
{"NeutronError": {"message": "Quota exceeded for resources: ['listener'].", "type": "OverQuota", "detail": ""}}
```

Watching if the service has a public IP works as well, but for better error reporting it would be great to get the precise issue.

```yaml
- name: Get an existing Service object
  community.kubernetes.k8s_event_info:
    api_version: v1
    kind: Service
    name: web
    namespace: testing
  register: web_service
```

**Comment by stiller-leser** [comment]
From looking at https://github.com/openshift/openshift-restclient-python/blob/master/openshift/dynamic/client.py it seems the openshift client does not support this yet, right?

**Comment by stiller-leser** [comment]
Well, turns out events can be retrieved via

```
- name: Fetching events
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Event
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: events
``` 

This allows to formulate the following `json_query`:

```
name: Getting PVC events
  set_fact:
    pvc_events: " {{ events | json_query(events_query) }} "
  vars:
    events_query: "resources[?involvedObject.apiVersion == `v1` && involvedObject.kind == `PersistentVolumeClaim` && involvedObject.name==`{{ pvc['resources'][0]['metadata']['name'] }}`].{ firstTimestamp: firstTimestamp, lastTimestamp: lastTimestamp, count: count, reason: reason, message: message }"
```

So, yes events can already be retrieved, but the `json_query` is very cumbersome. It would be nice to have a wrapper for it.
