### ISSUE TITLE
release_namespace is required even when chart already has a default namespace

### ISSUE THREAD

**Issue by memelet** [ansible-collections/community.kubernetes#272]
I'm deploying the rancher-monitoring (https://github.com/rancher/charts/tree/main/charts/rancher-monitoring). It by default will use the namespace `cattle-monitoring-system`, which I am happy with. The chart supports overriding the namespace with the value `namespaceOverride`

But I _must_ provide the `release_namespace` as it's required. To ensure that I keep the namespace consistent I am doing

```
- name: Install rancher-monitoring
  vars:
    namespace: cattle-monitoring-system
  helm:
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ kafka_strimzi_version }}"
    release_name: rancher-monitoring
    release_namespace: "{{ namespace }}"
    release_values:
      namespaceOverride: "{{ namespace }}"
```

Seems a bit smelly that I _must_ provide `release_namespace` given that charts can behave this way.
