### ISSUE TITLE
k8s update SecurityContextConstraint users list without specifying whole list

### ISSUE THREAD

**Issue by el-pako** [ansible-collections/community.kubernetes#287]
##### SUMMARY
I am unable to add a users list entry to the non-custom Kubernetes resource named 'privileged' of kind SecurityContextConstraint without overwriting all existing users list entries, as strategic-merge does not work.

##### ISSUE TYPE
- Bug Report / Usage error?

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION
```
ansible 2.9.14
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
None
```

##### OS / ENVIRONMENT
/bin/pip3 show openshift
```
Name: openshift
Version: 0.11.2
Summary: OpenShift python client
Home-page: https://github.com/openshift/openshift-restclient-python
Author: OpenShift
Author-email: UNKNOWN
License: Apache License Version 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: jinja2, kubernetes, python-string-utils, ruamel.yaml, six
```

Kubernetes environment is Openshift:
```
Server Version: 4.3.35
Kubernetes Version: v1.16.2+7279a4a
```

##### STEPS TO REPRODUCE
The 'privileged' SecurityContextConstraints in the K8s environment contains a list of users. After executing the following task, the users list contains only one entry: "system:serviceaccount:myproject:default"

```
- name: Add default service account user to privileged SCC
  k8s:
    definition:
      kind: SecurityContextConstraints
      metadata:
        name: privileged
      users:
      - "system:serviceaccount:myproject:default"
```

The task fails when explicitly specifying strategic-merge as the merge_type:

```
- name: Add default service account user to privileged SCC
  k8s:
    merge_type: strategic-merge
    definition:
      kind: SecurityContextConstraints
      metadata:
        name: privileged
      users:
      - "system:serviceaccount:myproject:default"
```

##### EXPECTED RESULTS
User "system:serviceaccount:myproject:default" is added to the list of users in the 'privileged' SCC, while keeping already listed users.

##### ACTUAL RESULTS
Either a list with only 1 user or the following exception when explicitly specifying strategic-merge.

```

fatal: [<remote_ip>]: FAILED! => {
    "changed": false,
    "error": 415,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "append_hash": false,
            "apply": false,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": null,
            "force": false,
            "host": null,
            "kind": null,
            "kubeconfig": null,
            "merge_type": [
                "strategic-merge"
            ],
            "name": null,
            "namespace": null,
            "password": null,
            "proxy": null,
            "resource_definition": {
                "apiVersion": "security.openshift.io/v1",
                "kind": "SecurityContextConstraints",
                "metadata": {
                    "name": "privileged"
                },
                "users": [
                    "system:serviceaccount:myproject:default"
                ]
            },
            "src": null,
            "state": "present",
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "msg": "Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml\",\"reason\":\"UnsupportedMediaType\",\"code\":415}\\n'",
    "reason": "Unsupported Media Type",
    "status": 415
}

```
