### ISSUE TITLE
k8s module quotes integer variables

### ISSUE THREAD

**Issue by andiolsi** [ansible-collections/community.kubernetes#290]
##### SUMMARY
The k8s module incorrectly quotes entries such as port and replicas when they are read from a dict using jinja2 templating

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```
ansible 2.9.11
  config file = /Users/myuser/.ansible.cfg
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.11/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### OS / ENVIRONMENT
Mac OS X 10.15.6

##### STEPS TO REPRODUCE

Define variables
```yaml
dict_with_service_info:
  - name: serviceX
     service-name: service-X
     replicas: 1
  - name: serviceY
     service-name: service-Y
     replicas: 2
```

create playbook
```yaml
---
- hosts: k8smaster
  tasks:
  - name: Create service object
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{item.service_name}}"
          namespace: default
          labels:
            run: "{{item.service_name}}"
        spec:
          selector:
            run: "{{item.service_name}}"
          ports:
          - protocol: TCP
            targetPort: 8080
            port: 8080
    loop: "{{dict_with_service_info | flatten(1)}}"
  - name: Deploy PODs
    vars:
      name: sv_cache
      service_name: service-cache
      replicas: 2
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: "{{item.service_name}}"
          namespace: default
        spec:
          selector:
            matchLabels:
              run: "{{item.service_name}}"
          replicas: "{{item.replicas}}"
          template:
            metadata:
              namespace: default
              labels:
                run: "{{item.service_name}}"
            spec:
              containers:
                - name: "{{item.service_name}}"
                  image: "nginx:latest"
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 8080
    loop: "{{dict_with_service_info | flatten(1)}}"
```

##### EXPECTED RESULTS
```
TASK [some-services : Deploy PODs] **********************************************************************************************************
changed: [k8smaster]
```

##### ACTUAL RESULTS
replicas gets quoted
```
ASK [some-services : Deploy PODs] **********************************************************************************************************
failed: [k8smaster] (item={'

....
v1.DeploymentSpec.Replicas: readUint32: unexpected character: \\ufffd, error found in #10 byte of ...|eplicas\\\":\\\"1\\\"

```

The same will be the case if you do:
```
replicas: "{{variable | to_json | from_json | int}}"
```

Whereas the following works:
```
replicas: "{{variable}}"
```

**Comment by tima** [comment]
@andiolsi Have you tried this: `replicas: "{{ item.replicas | int }}"`?

**Comment by andiolsi** [comment]
yes, absolutely, even ```replicas: "{{variable | to_json | from_json | int}}"```does have the same issue

**Comment by andiolsi** [comment]
i was told that each modules code should have something like
```'replicas': dict(type='int' ....```
to sanitize json creation.

it actually should even make a string "8080" into a unquoted integer when creating the request to kuberentes.

the k8s module does not do this

**Comment by andiolsi** [comment]
Found something else.
If you set an environment variable:
```
spec:
  containers:
    - name: foobar
       env:
         - name: TEST_ENVIRONMENT_VARIABLE_LISTENING_PORT_FOR_PROGRAM_IN_POD
            value: 8080
```

You get:
```
 ReadString: expects \\\" or n, but found 8, error found in #10 byte of ...|,\\\"value\\\":8080}],\\\"ima|..., bigger context ...|alue\\\":\\\"olsitrack\\\"},{\\\"name\\\":\\\"LISTEN_PORT\\\",\\\"value\\\":8080}],\\\"image\\\":\\\"registry.olsitec.de:20443/olsitrack|...\",\"field\":\"patch\"}]},\"code\":422}\n", "reason": "Unprocessable Entity", "status": 422
```

In this case it is non fatal as basically every linux environment variable is a string and every application that wants to treat it like an integer has to read and typecast it.

The k8s module code should auto-quote all "value" items that are passed in "env:"

I am a little astonished, that noone has stumbled across this.  It would seem I am the first person to use ansible to deploy items to a kubernetes cluster in a more abstractly configured way.  Or at least I am the first one to report it. (Or someone else did and I could not find that here.)

If you are handling multiple services/pods of the same function (microservices) then it es rather likely that you would have stored the amount of replicas in a variable.  It seems very likely that this variable is inside a dictionary.
