### ISSUE TITLE
Module for creating Job from CronJob

### ISSUE THREAD

**Issue by stanislaw55** [ansible-collections/community.kubernetes#292]
##### SUMMARY

It may be very specific use case but I need to create Job using CronJob object. Right now, I have to resort to `command` module in order to do that:
```yaml
- name: Test my CronJob
  command: kubectl --namespace {{ namespace }} job --from=cronjob/my-cron test-job
  register: test_job
  failed_when:
    - test_job.rc != 0
    - "already exists" not in test_job.stdout
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s_job

##### ADDITIONAL INFORMATION

One use case would be to test CronJobs that are running very seldom. Other use case may that: there's already defined but complicated CronJob for some task i.e. creating backup from database. Creating Job from CronJob allows performing this action on demand.

```yaml
- name: Test CronJob using Job
  k8s_job:
    name: test-job
    from_cronjob: some-cronjob
    state: present
```
this module would need also other options from `k8s` module like for waiting and validation.

This is just very loose idea - it may be better to create more generic module or completely restructure my proposal in case of being generic.

**Comment by Akasurde** [comment]
@stanislaw55 Thanks for reporting this issue. Why not use existing `k8s` module like 

```yaml
---
- hosts: localhost
  tasks:

    - name: Create a Job
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: myjob
            namespace: default
          spec:
            template:
              spec:
                containers:
                - image: nginx
                  name: myjob
                restartPolicy: Never
```

```
TASK [Create a Job] ***************************************************************************
task path: /Volumes/data/src/playbooks/k8s/k8s_job_v2.yml:5
changed: [localhost] => {"changed": true, "method": "create", "result": {"apiVersion": "batch/v1", "kind": "Job", "metadata": {"creationTimestamp": "2020-11-05T10:36:50Z", "labels": {"controller-uid": "3290ba73-702b-40e5-b82e-82fc6f8115d1", "job-name": "myjob"}, "name": "myjob", "namespace": "default", "resourceVersion": "5477061", "selfLink": "/apis/batch/v1/namespaces/default/jobs/myjob", "uid": "3290ba73-702b-40e5-b82e-82fc6f8115d1"}, "spec": {"backoffLimit": 6, "completions": 1, "parallelism": 1, "selector": {"matchLabels": {"controller-uid": "3290ba73-702b-40e5-b82e-82fc6f8115d1"}}, "template": {"metadata": {"creationTimestamp": null, "labels": {"controller-uid": "3290ba73-702b-40e5-b82e-82fc6f8115d1", "job-name": "myjob"}}, "spec": {"containers": [{"image": "nginx", "imagePullPolicy": "Always", "name": "myjob", "resources": {}, "terminationMessagePath": "/dev/termination-log", "terminationMessagePolicy": "File"}], "dnsPolicy": "ClusterFirst", "restartPolicy": "Never", "schedulerName": "default-scheduler", "securityContext": {}, "terminationGracePeriodSeconds": 30}}}, "status": {}}}
```

```
# kubectl get job
NAME    COMPLETIONS   DURATION   AGE
myjob   0/1           8s         8s
```

**Comment by stanislaw55** [comment]
Hi @Akasurde 
thanks for rapid response. 

Your advise is completely valid but in my case I have pretty complex CronJob manifest which is stored in different repository. So basically it would be hard to reuse it. Or I would have to copy manifest and adjust it for Job which what I'm avoiding by using `kubectl`.

The goal was to have something as simple as `kubectl job --from=cronjob/my-cron test-job` - in that case you can define CronJob *once*, in one place, and just create a Job from that CronJob. Basically perfect code reusage.

I do know that it might be very hermetic usage and my idea might not interesting for many. I created this issue mainly to see if others may need this functionality as well.

**Comment by tima** [comment]
I think I understand the problem and the convenience of `--from=cronjob/my-cron-test-job`. I'm not opposed to a `k8s_job` module if it provides more functionality or benefit than what can be done in `k8s` or without dropping in `shell`. 

This proposal is for this one very specific feature. What other features would this module that wouldn't be as easy using just `k8s`? Perhaps a module named something more like `k8s_exec_job` would be more appropriate if there's not much more. `k8s_job` implies something broader and more versatile in scope.

**Comment by stanislaw55** [comment]
> I'm not opposed to a `k8s_job` module if it provides more functionality or benefit than what can be done in `k8s` or without dropping in `shell`.

I agree that `k8s_job` module should provide more functionality than what I described. Currently I do not see anything more that can be added so maybe name `k8s_exec_job` or `k8s_launch_job` or `k8s_run_job` would be better (since `exec` already has a meaning in Kubernetes context).

For sake of completeness, I'm attaching my whole workaround

```yaml
- name: Create test Job
  command: kubectl --namespace {{ namespace }} create job --from=cronjob/my-cronjob test-job
  register: test_job
  failed_when:
    - test_job.rc != 0
    - '"already exists" not in test_job.stdout'

- name: Wait for job to finish
  command: kubectl --namespace {{ namespace }} wait --timeout=360s --for=condition=complete job/test-job
```

Another approach would to combine `k8s_info` and `k8s` modules: get pod template spec from CronJob using `k8s_info`, register output as variable and use it as a part of `definition` field for Job created by `k8s` module. I did not test that yet.

**Comment by Akasurde** [comment]
@stanislaw55 Thanks for information. Could you please following - 

```yaml
---
- hosts: localhost
  tasks:
    - set_fact:
        my_data: "{{ mydata | default({}) | combine({ item | basename : lookup('file', item) }) }}"
      with_fileglob: "config/*"

    - name: Create app config
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: game-demo
            namespace: default
          data: "{{ my_data }}"
```

```
# kubectl get configmaps game-demo -o yaml
apiVersion: v1
data:
  server.conf: |-
    tcp-port = 7180
    udp-port = 7182
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-02T13:13:55Z"
  name: game-demo
  namespace: default
  resourceVersion: "7489365"
  selfLink: /api/v1/namespaces/default/configmaps/game-demo
  uid: 730748cc-5d6b-46d4-9bee-a72343855d2b
```
