### ISSUE TITLE
lookup and module_defaults

### ISSUE THREAD

**Issue by er1z** [ansible-collections/community.kubernetes#335]
Don't know where to classify this issue. Is it possible to have following to be successful?

```
- name: k8s stuff
  module_defaults:
    set_fact:
      api_key: '{{kube_api_key}}'
      host: '{{kube_host}}'
  block:
    - name: Fetch a list of namespaces
      set_fact:
      projects: "{{ lookup('community.kubernetes.k8s', api_version='v1', kind='Namespace') }}" 
```

or should I specify `api_key` and `host` arguments every time?
