### ISSUE TITLE
"Unprocessable Entity", "status": 422

### ISSUE THREAD

**Issue by thanos1983** [ansible-collections/community.kubernetes#336]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
<!--- Explain the problem briefly below -->
I am trying to use the module [community.kubernetes.k8s – Manage Kubernetes (K8s) objects][1] with variables from the role (e.g. role/sampleRole/vars file).

I am failing when it comes to the integer point e.g.:

```yaml
- name: sample                                                                                                                                                         
  community.kubernetes.k8s:                                                                                                                                                                                                                      
  state: present                                                                                                                                                                                                                               
  definition:                                                                                                                                                                                                                                    
    apiVersion: apps/v1                                                                                                                                                                                                                          
    kind: Deployment                                                                                                                                                                                                                             
    metadata:                                                                                                                                                                                                                                      
      name: "{{ name }}"
      namespace: "{{ namespace }}"                                                                                                                                                                                             
      labels:
        app: "{{ app }}"                                                                                                                                                                                              
    spec:
      replicas: 2
        selector:
          matchLabels:
            app: "{{ app }}"                                                                                                                                                                                    
        template:
          metadata:
            labels:
              app: "{{ app }}"                                                                                                                                                                                
          spec:
            containers:
            - name: "{{ name }}"                                                                                                                                                                                  
              image: "{{ image }}"                                                                                                                                                                                
              ports:
              - containerPort: {{ containerPort }}
```

When I deploy with this format obviously it will fail at it can not parse the "reference" to the var.

Sample of error:

```bash
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')

The error appears to be in 'deploy.yml': line <some line>, column <some column>, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

              ports:
              - containerPort: {{ containerPort }}
                                ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

When I use quotes on the variable e.g. `- containerPort: "{{ containerPort }}"` then I get the following error (part of it):

```bash
v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Ports: []v1.ContainerPort: v1.ContainerPort.ContainerPort: readUint32: unexpected character: \\\\ufffd, error found in #10 byte of ...|nerPort\\\\\":\\\\\"80\\\\\"}]}],\\\\\"d|..., bigger context ...|\\\\\",\\\\\"name\\\\\":\\\\\"samplegreen\\\\\",\\\\\"ports\\\\\":[{\\\\\"containerPort\\\\\":\\\\\"80\\\\\"}]}],\\\\\"dnsPolicy\\\\\":\\\\\"ClusterFirst\\\\\",\\\\\"restartPolicy\\\\\"|...\",\"field\":\"patch\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```

I tried to cast the string to int by using `- containerPort: "{{ containerPort | int }}"` but it did not worked. The problem seems to be coming from the quotes, independently how I define the var in my var file e.g. `containerPort: 80` or `containerPort: "80"`.

I found a similar question on the forum stackoverflow [Ansible, k8s and variables][2] but the user seems not to have the same problems that I am having.

I am running with the latest version of the module:

```bash
$ pip3 show openshift
Name: openshift
Version: 0.11.2
Summary: OpenShift python client
Home-page: https://github.com/openshift/openshift-restclient-python
Author: OpenShift
Author-email: UNKNOWN
License: Apache License Version 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: ruamel.yaml, python-string-utils, jinja2, six, kubernetes
```

Is there any workaround this problem or is it a bug?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
module [community.kubernetes.k8s – Manage Kubernetes (K8s) objects][1]

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```bash
$ pip3 show ansible
Name: ansible
Version: 2.10.4
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: ansible-base
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
$ ansible-config dump --only-changed
ANSIBLE_COW_SELECTION(/home/<user>/my-cookbook/ansible.cfg) = random
ANSIBLE_NOCOWS(/home/<user>/my-cookbook/ansible.cfg) = False
DEFAULT_LOCAL_TMP(/home/<user>/my-cookbook/ansible.cfg) = /tmp/ansible-local-2287wsxqo1fo
DEFAULT_STRATEGY(/home/<user>/my-cookbook/ansible.cfg) = linear
DEPRECATION_WARNINGS(/home/<user>/my-cookbook/ansible.cfg) = False
HOST_KEY_CHECKING(/home/<user>/my-cookbook/ansible.cfg) = False
INTERPRETER_PYTHON(/home/<user>/my-cookbook/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->
Simply create a small demo and try to deploy on a master node.


<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: sample                                                                                                                                                         
  community.kubernetes.k8s:                                                                                                                                                                                                                      
  state: present                                                                                                                                                                                                                               
  definition:                                                                                                                                                                                                                                    
    apiVersion: apps/v1                                                                                                                                                                                                                          
    kind: Deployment                                                                                                                                                                                                                             
    metadata:                                                                                                                                                                                                                                      
      name: "{{ name }}"
      namespace: "{{ namespace }}"                                                                                                                                                                                             
      labels:
        app: "{{ app }}"                                                                                                                                                                                              
    spec:
      replicas: 2
        selector:
          matchLabels:
            app: "{{ app }}"                                                                                                                                                                                    
        template:
          metadata:
            labels:
              app: "{{ app }}"                                                                                                                                                                                
          spec:
            containers:
            - name: "{{ name }}"                                                                                                                                                                                  
              image: "{{ image }}"                                                                                                                                                                                
              ports:
              - containerPort: "{{ containerPort }}"
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
Expected result would be that the module can parse the string (or casted int) and not produce this error.

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```bash
v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Ports: []v1.ContainerPort: v1.ContainerPort.ContainerPort: readUint32: unexpected character: \\\\ufffd, error found in #10 byte of ...|nerPort\\\\\":\\\\\"80\\\\\"}]}],\\\\\"d|..., bigger context ...|\\\\\",\\\\\"name\\\\\":\\\\\"samplegreen\\\\\",\\\\\"ports\\\\\":[{\\\\\"containerPort\\\\\":\\\\\"80\\\\\"}]}],\\\\\"dnsPolicy\\\\\":\\\\\"ClusterFirst\\\\\",\\\\\"restartPolicy\\\\\"|...\",\"field\":\"patch\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```

  [1]: https://docs.ansible.com/ansible/latest/collections/community/kubernetes/k8s_module.html
  [2]: https://stackoverflow.com/questions/55821144/ansible-k8s-and-variables

**Comment by goneri** [comment]
Hi @thanos1983,

The problem seems to actually be this error: `readUint32: unexpected character: \\\\ufffd, error found in #10 byte of ...|nerPort`. It looks like you've got some unexpected characters either in the variable configuration file or maybe in the playbook itself. These UTF8 characters are not displayed by text-editor and may be hard to find.

**Comment by thanos1983** [comment]
> Hi @thanos1983,
> 
> The problem seems to actually be this error: `readUint32: unexpected character: \\\\ufffd, error found in #10 byte of ...|nerPort`. It looks like you've got some unexpected characters either in the variable configuration file or maybe in the playbook itself. These UTF8 characters are not displayed by text-editor and may be hard to find.

Hello @goneri,

I do not think that the problem is there. In my vars file I pass the variable as e.g.:

```yaml
containerPort: 80
```

I tried also to pass it as string e.g.:

```yaml
containerPort: "80"
```

Then I cast it to int e.g.:

```yaml
containerPort: "{{ containerPort | int }}"
```

But none of them worked.

My workaround for the moment is that I am using templates with the module e.g. (from documentation examples):

```yaml
- name: Read definition template file from the Ansible controller file system
  community.kubernetes.k8s:
    state: present
    template: '/testing/deployment.j2'
```

Where I can pass the variables without any problems. I think the error is misleading but it is up to you to close the ticket if you can not replicate it :).

BR / Thanos
