### ISSUE TITLE
helm_repository add repo failed with auth

### ISSUE THREAD

**Issue by PengBAI** [ansible-collections/community.kubernetes#337]
##### SUMMARY
use module helm_repository to add helm repo
```
- name: Add default repository
  community.kubernetes.helm_repository:
    name: "{{ helm_repo_name }}"
    repo_url: "{{ helm_repo_url }}"
    repo_username: "{{ helm_repo_username }}"
    repo_password: "{{ helm_repo_password }}"
```
the first time of run playbook is OK.
the second time is failed with
```
FAILED! => {"changed": false, "msg": "Repository already have a repository named xxxx"}
```

##### ISSUE TYPE
- bug

##### ANSIBLE VERSION

```
ansible 2.9.14
  config file = /home/vagrant/workspace/kazan-ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Aug  4 2020, 11:16:42) [GCC 9.3.0]

```

##### CONFIGURATION

```ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = xxxxx
MAX_FILE_SIZE_FOR_DIFF(env: ANSIBLE_MAX_DIFF_SIZE) = 360000

```

##### OS / ENVIRONMENT
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

##### STEPS TO REPRODUCE

1. run playbook with auth:
ex:
```
- name: Add default repository
  community.kubernetes.helm_repository:
    name: "{{ helm_repo_name }}"
    repo_url: "{{ helm_repo_url }}"
    repo_username: "{{ helm_repo_username }}"
    repo_password: "{{ helm_repo_password }}"
```
2. run a second time

```yaml

```

##### EXPECTED RESULTS

from the second time, playbook pass with ok, no changed.

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "msg": "Repository already have a repository named xxxx"}
```
