### ISSUE TITLE
Add hint for `pod/exec` RBAC resource to `k8s_exec`

### ISSUE THREAD

**Issue by stiller-leser** [ansible-collections/community.kubernetes#339]
##### SUMMARY
When working with limited RBAC rules and the `k8s_exec` module it would be very helpful to be aware of the requirement to add 
```
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
 ```
to the RBAC rule. I for one was not aware of the sub-resouces.

Happy to add it myself, but I am not sure how the documentation is generated.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

community.kubernetes.k8s_exec
