### ISSUE TITLE
Add context argument to k8s_cluster_info module

### ISSUE THREAD

**Issue by uda** [ansible-collections/community.kubernetes#340]
##### SUMMARY
Add context argument to the `k8s_cluster_info` module so I can get the relevant cluster's info (like version)

Currently this module only gives me the option to get the info of the default context.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/modules/k8s_cluster_info.py

##### ADDITIONAL INFORMATION
```yaml
- k8s_cluster_info:
    context: cluster-name
```

**Comment by gravesm** [comment]
@uda Thank you for posting this. Would you be willing to submit a PR for this feature?

**Comment by Akasurde** [comment]
@uda This is already supported. Can you please try like - 

```
#  kubectl config get-contexts
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*         cluster2   cluster2   cluster2
          minikube   minikube   minikube
```

```yaml
---
- hosts: localhost
  tasks:
    - community.kubernetes.k8s_cluster_info:
        context: cluster2
```

I hope this solves your requirement.

needs_info
-waiting_on_contributor
