### ISSUE TITLE
Secret keys are printed on error

### ISSUE THREAD

**Issue by ecksun** [ansible-collections/community.kubernetes#364]
##### SUMMARY
When I run `helm` and get a hook error it prints a secret (which I expect to be hidden)

Since I'm running ansible-playbook as part of a jenkins job I have to hide the output (`no_log: True`).

My chart does not have a secret in it, it only references one (deployed manually via another ansible task)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.kubernetes.helm

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /home/user/code/devops/ansible/cloud-infrastructure/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/code/devops/ansible/.venv/lib/python3.7/site-packages/ansible
  executable location = /home/user/code/devops/ansible/.venv/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
INTERPRETER_PYTHON(/home/user/code/devops/ansible/cloud-infrastructure/ansible.cfg) = ../.venv/bin/python3
```

##### STEPS TO REPRODUCE

```yaml
- name: Install latest available Helm chart in current channel
  community.kubernetes.helm:
    name: cloud-engine
    chart_ref: "{{ helm_gcs_bucket }}/proj"
    chart_version: '>0.0.0-0' # Get devel versions
    release_namespace: default
    update_repo_cache: true
    atomic: true
    wait: true
```

##### EXPECTED RESULTS

I expect that no secret would be output onto the console.

It would be preferable to not get any output (unless some -v is specified perhaps?) than to have my secrets leak into logs.

##### ACTUAL RESULTS

```paste below
TASK [applications/proj : Install latest available proj Helm chart in current channel] 
fatal: [localhost]: FAILED! => {"changed": false, "command": "/home/user/bin/helm --namespace=default --version=>0.0.0-0 upgrade -i --reset-values --wait --atomic -f=/tmp/tmpkuwixan5.yml proj nh-helm-unstable/proj", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: pre-upgrade hooks failed: timed out waiting for the condition: warning: Hook post-rollback proj/templates/hooks/db-migrate-job.yaml failed: Job.batch \"proj-db-migrate\" is invalid: [spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.name: Invalid value: \"map[apiVersion:v1 data:map[cloud-sql-proxy.service-account-credentials:LONG SECRET HERE  [CUT A BUNCH OF TEXT]: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]"], "stdout": "", "stdout_lines": []}
```
