### ISSUE TITLE
Allow templates to be passed directly through to k8s module

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.kubernetes#37]
##### SUMMARY

Frequently, when using the `k8s` module to apply a Kubernetes manifest, I have a manifest template with one or more resource definitions that I would like to have templated via Ansible/Jinja.

The current way I do this is:

```yaml
    - name: Create app resources.
      k8s:
        definition: '{{ item }}'
        state: present
      loop:
        - "{{ lookup('template', 'templates/app.yml.j2') | from_yaml_all | list }}"
```

It seems like it would be much simpler to have a `template` option for `k8s` which would use Ansible's `Templar` (only available if the template is being passed through on localhost, I guess, since it can't be templated if running as a module on the remote host (or can it?)) to parse and template the manifest file:

```yaml
    - name: Create app resources.
      k8s:
        template: templates/app.yml.j2
        state: present
```

This feature request was originally posted in the ansible/ansible repo here: https://github.com/ansible/ansible/issues/60134

That issue's original description (from @chris-short):

> I think it'd be beneficial for the k8s module (and subsequently operator-sdk) to avoid using Jinja2 templating when possible. In a nutshell, I'd like a cleaner, simpler way to invoke templating of k8s YAML files as their deployed via Ansible. Example of the current state: https://github.com/geerlingguy/mcrouter-operator/blob/a3babecae85ece431f5cf316bd8a407ba60a5b42/roles/mcrouter/tasks/main.yml
> 
> It's 431 bytes in total, I get that. It's not a lot of Jinja2, I get that too. Jinja2 is another thing to add on to the pile of things to learn before you can harness it and removing that barrier will be beneficial. The effort of learning Jinja2 for this use case (globally) far outstrips our effort to help solve this problem on behalf of our users.
> 
> The overarching goal is to minimize the amount of Jinja2 needed in playbooks to make this work.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

k8s

##### ADDITIONAL INFORMATION

Please see the earlier discussion in https://github.com/ansible/ansible/issues/60134 for more background (especially why this could be challenging to implement, or involve a few caveats).
