### ISSUE TITLE
Support globally the "ansible_kubectl_context" variable

### ISSUE THREAD

**Issue by goetzc** [ansible-collections/community.kubernetes#372]
##### SUMMARY
Just as many modules support the `K8S_AUTH_CONTEXT` environment variable, globally supporting the `ansible_kubectl_context` variable would be handy.

Such as here:
https://github.com/ansible-collections/community.kubernetes/blob/0377a892d5ce7ee39ad683d80be8be58dbef7360/plugins/connection/kubectl.py#L83-L90

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community.kubernetes.*`

##### ADDITIONAL INFORMATION
When there are multiple contexts available, instead of always having to specify the context on every task/modules, just as the `K8S_AUTH_CONTEXT` allows to set a global context used on all k8s operations. 

```yaml
  name: Foo
  k8s:
    state: present
    context: my_context  # ← This line
    namespace: default
    definition:
      …
```
