### ISSUE TITLE
Seamless handling of ansible vaulted files in K8s modules

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#38]
##### SUMMARY

The `kubeconfig` parameter in the k8s module and all others such seamless detect and decrypt ansible-vault'ed files.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

module_utils/common.py (This seems to be where the underlying logic is handled.)

##### ADDITIONAL INFORMATION

If you are storing a kubeconfig file in a repo -- maybe you are working with multiple clusters or perhaps its for a service account. Whatever the reason you don't want to store that in plain text where anyone can read those credentials and use them to control the associated cluster.

Using `ansible-vault` rectifies this by encrypting the credentials away from prying eyes so only those with the passphrase can use what's there.

Unfortunately I found out the hard way that the `kubeconfig` parameter in the `k8s` module (and really many others) cannot work with `ansible-vault` encrypted files.

Here is what I had to do work around not having that feature:

```yaml
    - name: prepare api access config
      template:
        src: kubeconfig.j2
        dest: kubeconfig.tmp
        mode: '0400'
    - name: define cache service resource
      k8s:
        state: "{{ cache_service_state | default(omit) }}"
        definition: "{{ lookup('template', 'k8s-cache-service-def.yaml.j2') | from_yaml }}"
        kubeconfig: kubeconfig.tmp
    - name: remove kubeconfig.tmp
```
Where `kubeconfig.j2` simply contained this:

```yaml
{{ lookup('file', k8s_kubeconfig_src) }}
```
This caused ansible to decrypt the vaulted kubeconfig file and write it out to a temp file that could be read in by the k8s module to issue its API. It's flawed because for a brief moment the credential is exposed though only the user running the playbook can read that temp file.

Ideally I would have like to have just done something like:

```yaml
    - name: define cache service resource
      k8s:
        state: "{{ cache_service_state | default(omit) }}"
        definition: "{{ lookup('template', 'k8s-cache-service-def.yaml.j2') | from_yaml }}"
        kubeconfig: "{{ k8s_kubeconfig_src }}"
```

Where Ansible would read the kubeconfig file, catch that it's vault encrypted, decrypt it in memory and then proceed to execute API calls to the cluster with those credentials. No tempfile or one line template needed.
