### ISSUE TITLE
How to install a storageClass using this collection?

### ISSUE THREAD

**Issue by CodingSpiderFox** [ansible-collections/community.kubernetes#381]
##### SUMMARY
After deploying a new cluster with kubespray, it has no storageClasses at all and I want to use ansible to provision a default storageClass.

##### ISSUE TYPE
- Feature reqeust

##### ANSIBLE VERSION

```paste below
ansible 2.9.17
  config file = /home/user/Code/github.com/codingspiderfox/nas-config/hp-microserver-gen10-plus-ip-192-168-3-103/ansible/3rdparty/kubespray/ansible.cfg
  configured module search path = ['/home/user/Code/github.com/codingspiderfox/nas-config/hp-microserver-gen10-plus-ip-192-168-3-103/ansible/3rdparty/kubespray/library']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]

```

##### CONFIGURATION

```paste below
should not be relevant here
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

See kubespray documentation for setting up kubespray

```yaml

```

##### EXPECTED RESULTS

StorageClass is available in cluster

##### ACTUAL RESULTS

I can find nothing in the collection that would allow me to do that

```paste below

```

**Comment by geerlingguy** [comment]
@CodingSpiderFox - Typically you'd do that by deploying a StorageClass object / manifest using the module. The way a specific StorageClass is configured is very vendor/provider-specific. But in general, it is deployed using `k8s` just like any other resource in Kubernetes.

**Comment by Akasurde** [comment]
@CodingSpiderFox Like @geerlingguy said - 

```yaml
---
- hosts: localhost
  tasks:
    - name: Create a storage class
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-storage
            namespace: default
          provisioner: kubernetes.io/no-provisioner
          volumeBindingMode: WaitForFirstConsumer
```

Closed as per above.
