### ISSUE TITLE
Add roles to install Kubernetes

### ISSUE THREAD

**Issue by aharrisson** [ansible-collections/community.kubernetes#41]
##### SUMMARY

It would be interesting if this collection also included roles and playbook(s) for installing a cluster.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
roles

##### ADDITIONAL INFORMATION

To have a community supported and well structured set of roles to install Kubernetes with Ansible would be a good starting point for people with Ansible knowledge to create a Kubernetes cluster.
The initial effort could be to have a few simple roles to set up a cluster with very few options, but the collection could easily grow to support different scenarios.
Internally the roles could use the existing Ansible modules in the collection, where applicable.

```yaml
---
- hosts: kubernetes_nodes
  collections:
    - name: community.kubernetes
  roles:
    - role: kubernetes_node

- hosts: kubernetes_masters
  collections:
    - name: community.kubernetes
  roles:
    - role: etcd
    - role: kubernetes_master
```
