### ISSUE TITLE
Unusual k8s_info behavior with kubeconfig

### ISSUE THREAD

**Issue by danielburrell** [ansible-collections/community.kubernetes#414]
##### SUMMARY

There are 2 scenarios to be compared:
**CI Scenario:**
I have a CI environment where a clean control box is stood up, and a clean target box is stood up. CI will run the installer from the control box and install kubernetes to a target box as part of the playbook. The target box's kubeconfig file `~centos/.kube/config` is copied to the control box at the same location `~centos/.kube/config` near the end of the play. At all times everything runs as 'centos' user. When I run a k8s_info action in this scenario, specifying the kubeconfig file, I am able to confirm the existance of various deployments in my cluster.
`whoami` on all boxes would return `centos` and ansible_user would also return `centos`. The 2 boxes are basically the same, just different 'purpose'. This is the only scenario that works.

**Local Development Scenario**
I have a developer computer which acts as a control box, I am logged in as myself e.g. `daniel` there is a target box configured the same way as the CI scenario (with a centos user), when I run the installation, I set `-u centos`, the ssh user is `centos`, but I run the installer as `daniel`. so
`whoami` on the localhost would return `daniel` and anywhere else would be `centos`.
The kubeconfig file is in its place on the target machine, and this time gets copied to the control box. Note in the CI scenario, the copy was to an identical folder, `~centos/.kube/config`, but this time in this scenario, it's copied to `~daniel/.kube/config`

I only recently started using the local development scenario, and was under the impression that the kubeconfig was to be found on the target machine (not the control machine).

When I try to run a k8s_info action in this scenario specifying the kubeconfig file as `~centos/.kube/config` then it says the file cannot be found on the AnsibleControl machine.

If I switch to `~daniel/.kube/config` (which exists on the control machine), then it tells me that the config isn't valid!

```
failed: [10.50.52.94] (item={'name': 'coredns', 'quantity': 1}) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": {"name": "coredns", "quantity": 1}, "msg": "Failed to load kubeconfig due to Invalid kube-config file. No configuration found."}
```

```
ls ~/.kube/config
/home/daniel/.kube/config
```

```
cat ~/.kube/config

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redactedbase64==
    server: https://10.50.52.94:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: redacted
    username: redacted
```
This is all very strange, as this causes the playbook to fail, and I am able to cat the file, and it's perfectly valid, and works with kubectl.

Any ideas?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s_info

##### ANSIBLE VERSION

```paste below
[WARNING]: Ansible is being run in a world writable directory (/home/daniel/projects/prom/project), ignoring it as an ansible.cfg source. For more
information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
ansible-playbook 2.10.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/daniel/.pex/installed_wheels/04c26471cb05787fcd8372d2f2bea63afb042678/ansible_base-2.10.6-py3-none-any.whl/ansible
  executable location = ansible-playbook
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

centos 7.9

##### STEPS TO REPRODUCE

```yaml

- name: Copy kubeconfig from the server to the control machine
  fetch:
   # in CI both control_user_id and ansible_user are centos, in development, control_user_id is daniel, ansible_user is centos
    src: ~{{ ansible_user }}/.kube/config
    dest: ~{{ control_user_id }}/.kube/config
    flat: yes
  become: no

# SNIP
# run once on host 'server' (target)
- name: "Verify k3s deployment via ~{{ ansible_user }}/.kube/config"
  community.kubernetes.k8s_info:
    kind: Deployment
    wait: yes
    name: "{{ item.name }}"
    namespace: kube-system
    wait_timeout: 360
    wait_sleep: 10
   #apparently this kubeconfig file is supposed to be on the control box, can this be added to the docs?
    kubeconfig: "~{{ control_user_id }}/.kube/config" 
  register: deployment_status
  run_once: true
  become: yes
  until: (deployment_status.resources[0].status.readyReplicas | default(0) == item.quantity)
  retries: 5
  loop:
    - { name: 'coredns', quantity: 1 }
```

##### EXPECTED RESULTS

I would have expected my kubeconfig file to be considered valid

##### ACTUAL RESULTS

```paste below

```
