### ISSUE TITLE
Proxy param does not accept authentication header

### ISSUE THREAD

**Issue by senpai-d** [ansible-collections/community.kubernetes#416]
##### SUMMARY
When setting a proxy url in the proxy param, the username:password header is not read. It only accesses the URL, which returns a 407 if authentication is required for the proxy.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION
```paste below
ansible 2.9.0
   config file = /home/user/.ansible.cfg
   configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   ansible python module location = /home/user/projects/python_envs/ansible-env/lib/python3.6/site-packages/ansible
   executable location = /home/user/projects/python_envs/ansible-env/bin/ansible
   python version = 3.6.9 (default, Jan 26 2021, 15:33:00)
```

##### CONFIGURATION
```paste below
DEFAULT_ROLES_PATH(/home/user/.ansible.cfg) = ['/home/user/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
RETRY_FILES_ENABLED(/home/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
WSL Ubuntu 18.03
Pythion 3.6 virtual environment

##### STEPS TO REPRODUCE
With a proxy url such as http://USERNAME:PASSWORD@proxy.com:3001, the USERNAME:PASSWORD header is not loaded in, resulting in a 401 due to authentication required with proxy.

```yaml
- name: Set up namespace
  hosts: localhost
  tasks:
    - name: create namespace
      k8s:
        host: "https://kube-cluster.com"
        api_key: "api_token"
        proxy: "http://USERNAME:PASSWORD@proxy.com:3001"
        state: present
        name: "new-default-namespace"
        api_version: "v1"
        state: present
```

##### EXPECTED RESULTS
Expected for the namespace to be created.

##### ACTUAL RESULTS
Received a 407 from proxy server.

```paste below
kubernetes.client.rest.ApiException: (401)
Reason: authenticationrequired
```

The rest of the output is proxy server error being returned.
