### ISSUE TITLE
Add a diff option to k8s module 

### ISSUE THREAD

**Issue by Skull0ne** [ansible-collections/community.kubernetes#79]
##### SUMMARY
Is it possible to add to the k8s module a "diff" option to run a `kubectl diff` instead of a `kubectl apply`

I'm using this code to run a diff before applying my configuration : 
```
- name: kubectl diff config
  shell: >
    cat <(echo "$tmp_manifest") | {{ kubernetes_kubectl }} diff --kubeconfig=environments/{{ kubernetes_env }}/kubeconfigs/$(whoami).kubeconfig.yml -f - 2>&1
  args:
    executable: /bin/bash
  environment:
    tmp_manifest: "{{ lookup('template', 'roles/test/templates/test.yml.j2') }}"
  register: diff_output_secrets
  check_mode: false
  ignore_errors: true
  failed_when: false
```

##### ISSUE TYPE

```
- name: kubectl diff
  k8s:
    definition: "{{ lookup('template', 'roles/test/templates/test.yml.j2') }}"
    kubeconfig: "environments/{{ kubernetes_env }}/kubeconfigs/$(whoami).kubeconfig.yml"
    diff: true
```

##### COMPONENT NAME
k8s_module

##### ADDITIONAL INFORMATION

My role : 
```
- name: kubectl diff config
  shell: >
    cat <(echo "$tmp_manifest") | {{ kubernetes_kubectl }} diff --kubeconfig=environments/{{ kubernetes_env }}/kubeconfigs/$(whoami).kubeconfig.yml -f - 2>&1
  args:
    executable: /bin/bash
  environment:
    tmp_manifest: "{{ lookup('template', 'roles/test/templates/test.yml.j2') }}"
  register: diff_output_config
  check_mode: false
  ignore_errors: true
  failed_when: false

- name: show {{ kubernetes_kubectl }} diff config output
  debug:
    var: diff_output_config.stdout 
  when:
    - diff_output_config is defined and diff_output_config.stdout != ''
	
- name: "{{ kubernetes_kubectl }} apply config"
  k8s:
    state: present
    definition: "{{ lookup('file', 'environments/' + kubernetes_env + '/k8sconfigs/test.yml') }}"
    kubeconfig: "environments/{{ kubernetes_env }}/kubeconfigs/$(whoami).kubeconfig.yml"
  register: apply_config_output
  when:
    - diff_output_config is defined and diff_output_config.stdout != ''
```

Thanks
