### ISSUE TITLE
K8s module doesn't use context namespace which oblige complexity in code

### ISSUE THREAD

**Issue by elafontaine** [ansible-collections/community.kubernetes#83]
https://github.com/ansible/ansible/issues/51242#issuecomment-546444097
https://github.com/ansible/ansible/issues/69193
##### SUMMARY
`kubectl` and `oc` are assuming a default namespace on resources for which you do not define a "metadata.namespace" attribute.  This is the default behaviour of `kubectl` as it use the one defined in the configuration of a context required to authenticate to the kubernetes clusters (the context).  

A use case to have the namespace *not* specified on the resource being passed is that you might want to deploy those resources in differents namepaces depending on the `context` you're in (test namespace, production namespace, dev namespace, etc.).  

This is a pretty usual case where you want to ensure the resource work for a certain scenario in a development cluster and then move to a production cluster which uses a different namespace.  It ease the code complexity as you use the `kubectl` context (which uses "default" namespace by default, but you can point to the namespace you want).

A more extended use case is to have a test cases within the same cluster you're using ; a user with namespaced rights on the test namespace but with no access to the cluster wide.  The `context` is namespaced and it's able to do pretty much anything a cluster-admin would be able to do, but only on that namespace (create and patch of a namespace but only that namespace).  This enable to limit the blast radius of an error to only that namespace but still test the behaviour of your code.  It will also prevent extended access into other namespace.

I would like to re-open the [discussion](https://github.com/ansible/ansible/issues/51242) as I believe those strategy are relevants ones in combination with i.e. gitlab kubernetes integration which define a `context` for you to execute kubectl commands which encompass the namespace as well (as is the case with `kubectl` and `oc`).
It's also not an expected behaviour when you have a resource that you were able to deploy with kubectl and oc but not with ansible k8s module.

If the decision stays to be "it has to be explicitly defined and maintain in the code", than I believe the [documentation should be also explicit](https://docs.ansible.com/ansible/latest/modules/k8s_module.html#parameter-namespace) and be updated to say that all resource requiring a namespace will have to get the namespace defined within "resource definition" or "namespace" field.

##### ISSUE TYPE
- Feature Idea and/or documentation clarification

##### COMPONENT NAME
k8s module should use namespace from context when it's not passed to continue behaviour of the wrapper it's supposed to use. (aka `kubectl` and `oc`).

##### ADDITIONAL INFORMATION
Here is an example of a configmap that could be used with a deployment;
```bash
ansible-playbook example.yml
```
```yaml
- name: a ConfigMap for an app without metadata.namespace specified
  k8s:
    state: present
    definition: "{{ lookup('template', 'cm.yaml.j2') }}"
```
cm.yaml.j2
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
data:
  somedata: "Hello"
```

Current situation (will correct the bash later when I get on my work laptop) ;
```bash
ansible-playbook example.yml -e namespace=$(kubectl config view --minify --output 'jsonpath={..namespace}')
```
```yaml
- name: a ConfigMap for an app without metadata.namespace specified
  k8s:
    state: present
    definition: "{{ lookup('template', 'cm.yaml.j2') }}"
```
cm.yaml.j2
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: "{{ namespace }}"
data:
  somedata: "Hello"
```

some more references; 
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

**Comment by willthames** [comment]
My view is that making namespace non-optional is a safeguarding feature, not a bug, although one could make the same argument for context too (we actually have a context checker at the start of our playbooks to ensure that expected context matches to current context)

**Comment by elafontaine** [comment]
So, how do we start the discussion?

I would like to suggest that we ensure the namespace isn't "default" unless it's explicitly said to be default?  

I would like to ensure we find a good solution :).
My proposition;
- Safe guarding for *default* namespace (unless explicitly defined).  
- Use the context namespace when it's not explicitly defined and that it's not default

@willthames could you elaborate/share what is the "context matches to current context"?

**Comment by willthames** [comment]
@elafontaine I'd probably support an `enforce_namespace` which defaults to true - you could then use `enforce_namespace: false` - at that point how it works is not something I'm too fussy about (the check for default namespace seems unnecessary). Using [module_defaults](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html) would mean you'd only need to set that once. 

On my other point, I just mean that if I'm deploying using a virtual host of `application-test`, which lives in my `test` kubernetes cluster, I ensure that my context is also `test` - basically the `test` group has `kube_cluster_name: test` and then I do `kubectl config current-context` and ensure the output matches `kube_cluster_name`

**Comment by elafontaine** [comment]
👍 love the idea of having it configurable with a field.

I'm not sure I understand the 2nd paragraph... mind confirming my understanding?
On your personal playbook, you have pre-task to verify the context is matching?  If that's true, is it something you could share as well for people finding this discussion could do the same?

I think it's good, so if we were to update the library, to do as you've proposed and document the new field feature, would there be anything that would be left to do ?  Is it how we are to proceed?

**Comment by willthames** [comment]
```
- name: check current kubernetes cluster
  command: kubectl config current-context
  changed_when: false
  register: kubectl_current_context
  check_mode: no
  tags: always
  ignore_errors: yes  # this task fails on in-cluster nodes
  failed_when: no

- assert:
    that:
      - kubectl_current_context.stdout == kube_cluster_name
    msg: "Your kubernetes cluster is set to {{ kubectl_current_context.stdout }}. It should be {{ kube_cluster_name }}"
  when: kubectl_current_context.rc == 0
  tags: always
```

We can't necessarily assume that there is a context (because these tasks get run from inside and outside the cluster) so this has been the easiest way to enforce that we're running against the expected cluster
