### ISSUE TITLE
Helm support for single or multiple values files

### ISSUE THREAD

**Issue by telemaco** [ansible-collections/community.kubernetes#93]
##### SUMMARY

Could be interesting that the helm module will support single or multiple values files. 
Helm command itself support it adding "-f values.yaml -f values2.yaml"  
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

* helm

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by orjan** [comment]
Since the module is taking values we can combine the files with Ansible without having to use the built in support in helm for multiple files. I'll guess something like this might work?

```
---
- hosts: all
  vars:
    default_vars: "{{ lookup('template', 'default.yaml') | from_yaml }}"
    override_vars: "{{ lookup('template', 'production.yaml') | from_yaml }}"
  tasks:
    - name: Combine values
      debug:
        msg: "{{ default_vars | combine(override_vars) }}"
```

**Comment by loomsen** [comment]
I have a similar use case, where I have a common values file, and I'd like to define the overrides in the helm task in the playbook itself, to make it more readable. For example, prometheus could be installed with alertmanager in stg and prd, but without in dev. It would be nice to have a common file, and have tasks in the playbooks like:

```
        - name: install prometheus
          helm:
            chart: stable/prometheus
            name: prometheus
            namespace: monitoring
            values_file: /path/to/common/values.yml
            values:
                 alertmanager:
                   enabled: false
```

Would be nice to have a way to combine those, like for example a `values_file` parameter. I have tried to combine it in different ways, but none of them worked. So now either I have to have different template files for each environment, even though they might just differ in one line, or I would have massively long and unreadable playbooks, all due to the huge prometheus values.yaml when you define custom scrape configs and whatnot.
